title: "Computer Science Courses"
description: "Course materials for CS classes"
baseurl: "/programming"
url: "https://mssmcs.github.io"

# Build settings
theme: just-the-docs
color_scheme: light
search_enabled: true
heading_anchors: true

# Just the Docs settings
aux_links:
  "GitHub Repository":
    - "//github.com/mssmcs/programming"

# Default layout
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
