title: "Computer Science Courses"
description: "Course materials for CS classes"
baseurl: "/programming"
url: "https://mssmcs.github.io"

# Build settings
theme: jekyll-theme-cayman
permalink: pretty

# Default layout settings
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
